pipeline:
  type: Ingest

dataset_definition:  # Describes the dataset that will be produced
  attributes:
    title: Columbia Power Raw Power Data
    description: "Sample 5kHz raw power data to test tsdat ingest"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    #doi:
    institution: NREL
    code_url: https://github.com/clansing/tsdat/releases/tag/1.0
    location_id: NREL_flatirons_campus_CO
    instrument_id: Power Meter
    data_level: b1 # Data Levels section 7 standards, equivalent of a1 in doc
    #location_meaning:
    #instrument_name: 
    #instrument_meaning:
    #instrument_manufacturer: 
    #sampling_interval: 

  dimensions:
    time:
        length: unlimited

  variables:

    time:
      input:
        # Name of the variable in the raw data
        name: "Time"
        converter:
          classname: tsdat.utils.converters.TimestampTimeConverter
          parameters: # UTC/Unix Epoch https://www.epochconverter.com
            unit: ns # Unit of the numeric value as used by pandas.to_datetime (D,s,ms,us,ns)
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    MODAQ_Va:  
      input: 
        file_pattern: PowRaw
        name: MODAQ_Va
      dims: [time]
      type: double
      attrs:
        long_name:  MODAQ Phase A Voltage
        units: V
        #fail_range: 
    
    MODAQ_Vb:  
      input: 
        file_pattern: PowRaw
        name: MODAQ_Vb
      dims: [time]
      type: double
      attrs:
        long_name:  MODAQ Phase B Voltage
        units: V
        #fail_range: 

    MODAQ_Vc:  
      input: 
        file_pattern: PowRaw
        name: MODAQ_Vc
      dims: [time]
      type: double
      attrs:
        long_name:  MODAQ Phase C Voltage
        units: V
        #fail_range: 

    MODAQ_Ia:  
      input: 
        file_pattern: PowRaw
        name: MODAQ_Ia
      dims: [time]
      type: double
      attrs:
        long_name:  MODAQ Phase A Current
        units: A
        #fail_range: 

    MODAQ_Ib:  
      input: 
        file_pattern: PowRaw
        name: MODAQ_Ib
      dims: [time]
      type: double
      attrs:
        long_name:  MODAQ Phase B Current
        units: A
        #fail_range: 

    MODAQ_Ic:  
      input: 
        file_pattern: PowRaw
        name: MODAQ_Ic
      dims: [time]
      type: double
      attrs:
        long_name:  MODAQ Phase C Current
        units: A
        #fail_range:     

#-----------------------------------------------------------------
coordinate_variable_qc_tests:  # Define QC tests for coordinate variables

  missing:
    variables:
      - ALL
    operator:
      classname: tsdat.qc.operators.CheckMissing
    error_handlers:
      fail_pipeline:
        classname: tsdat.qc.error_handlers.FailPipeline

  monotonic:
    variables:
      - All
    operator:
      classname: tsdat.qc.operators.CheckMonotonic
    error_handlers:
      fail_pipeline:
        classname: tsdat.qc.error_handlers.FailPipeline

#-----------------------------------------------------------------

qc_tests:  # Define QC tests for non-coordinate variables

    missing:
        qc_bit: 1
        meaning: "Value is equal to _FillValue or NaN"
        assessment: Bad
        variables:
          - ALL  # keyword to apply test to all variables
        operator:
          classname: tsdat.qc.operators.CheckMissing
        error_handlers:
          # Replace any NaNs with _FillValue
          replace_with_fill_value:
            classname: tsdat.qc.error_handlers.RemoveFailedValues

    fail_min:
        qc_bit: 2
        meaning: "Value is less than the fail_range."
        assessment: Bad
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckFailMin
        error_handlers:
          replace_with_fill_value:
            classname: tsdat.qc.error_handlers.RemoveFailedValues

    fail_max:
        qc_bit: 3
        meaning: "Value is greater than the fail_range."
        assessment: Bad
        variables:
          - ALL
        operator:
          classname: tsdat.qc.operators.CheckFailMax
        error_handlers:
          replace_with_fill_value:
            classname: tsdat.qc.error_handlers.RemoveFailedValues
